A) Abfrage und Ausgabe aller Tabellen in der Datenbank aus dem vorhergehenden Beispiel: 
Die Tabellen sollen im Terminal in "formatierter" Form ausgegeben werden. Dabei soll ein Datenbank-Curser verwendet
und eine entsprechende Abfrage mittels cursor.execute() ausgeführt werden.
Die Tabellenüberschrift ist optisch - zumindest durch eine Trennzeile vom 
Tabelleninhalt zu trennen. Es sollen jeweils nur die ersten 5 Zeilen einer Tabelle ausgegeben werden.

In [13]:
import pandas as pd
import sqlite3
sqlite_db = r'C:\Users\Markus\Documents\GITHUB\Software_Programmierung\Schulsachen\3BWHII\INFI\A3\T1_Kunden_Mitarbeiter.db'
conn=sqlite3.connect(sqlite_db) 

# Creates sqlite Database - check in your file explorer
cur=conn.cursor()
cur.execute("SELECT name FROM sqlite_master WHERE type='table';")
mytables=cur.fetchall()
for row in mytables:
    print('''*********************************************\n
--      <<<<<<{row}>>>>>>\n
-----------------------------------------------'''.format(row=row))
    cur.execute("SELECT * FROM {retrieved_table};".format(retrieved_table=row[0]))
    table_data=cur.fetchmany(5)
    for detailrow in table_data:
        print(detailrow)
    print('*********************************************' )

*********************************************

--      <<<<<<('C_Mitarbeiter',)>>>>>>

-----------------------------------------------
(1, 'Norman', 'Brown')
(2, 'Joel', 'Jewett')
(3, 'Brandy', 'Nosek')
(4, 'Minnie', 'Porter')
(5, 'Fonda', 'Coleman')
*********************************************
*********************************************

--      <<<<<<('sqlite_sequence',)>>>>>>

-----------------------------------------------
('C_Mitarbeiter', 10)
('C_Kunden', 1141)
*********************************************
*********************************************

--      <<<<<<('C_Kunden',)>>>>>>

-----------------------------------------------
(1, 'Albert', 'Schwingenschloegl', 12)
(2, 'Albert', 'Schwingenschloegl', 12)
(11, 'Mark', 'Watts', 1)
(12, 'Juanita', 'Wheatley', 1)
(13, 'Eric', 'Taylor', 8)
*********************************************

In [14]:
cur.execute("SELECT ID, Nachname FROM C_Kunden;")
result=cur.fetchall()
for row in result:
    print(row)

(1, 'Schwingenschloegl')
(2, 'Schwingenschloegl')
(11, 'Watts')
(12, 'Wheatley')
(13, 'Taylor')
(14, 'Sandahl')
(15, 'Taylor')
(16, 'Gable')
(17, 'Smart')
(18, 'Whittle')
(19, 'Oman')
(20, 'Bolick')
(21, 'Kohler')
(22, 'Holguin')
(23, 'Rojo')
(24, 'Callahan')
(25, 'Mcintyre')
(26, 'Singleton')
(27, 'Gibson')
(28, 'Kowalski')
(29, 'Doney')
(30, 'Milligan')
(31, 'Samson')
(32, 'Brown')
(33, 'Pitts')
(34, 'Patterson')
(35, 'Paik')
(36, 'Samora')
(37, 'Crawford')
(38, 'Moore')
(39, 'Kaplan')
(40, 'Daniels')
(41, 'Harrington')
(42, 'Teal')
(43, 'Gonzalez')
(44, 'Perez')
(45, 'Higginbotham')
(46, 'Carignan')
(47, 'Medlock')
(48, 'Sorell')
(49, 'Hartz')
(50, 'Kaltz')
(51, 'Keagle')
(52, 'Ross')
(53, 'Jenkins')
(54, 'Parker')
(55, 'Pearson')
(56, 'Cantrell')
(57, 'Fass')
(58, 'Pugh')
(59, 'Kennard')
(60, 'Jackson')
(61, 'Bryant')
(62, 'Seifert')
(63, 'Aragon')
(64, 'Vaughn')
(65, 'Young')
(66, 'Hill')
(67, 'Harrison')
(68, 'Hock')
(69, 'Fortier')
(70, 'Jones')
(71, 'Jenkins')
(72, 'Bates')
(73, 'Reeves')
(74, 'Knowlton')
(75, 'Hill')
(76, 'Gomez')
(77, 'Miller')
(78, 'Pennington')
(79, 'Green')
(80, 'Lee')
(81, 'Billups')
(82, 'Shoemake')
(83, 'Parker')
(84, 'Williams')
(85, 'Bailey')
(86, 'Williams')
(87, 'Lee')
(88, 'Brooks')
(89, 'Dyches')
(90, 'Mcrae')
(91, 'Spooner')
(92, 'Johnson')
(93, 'Arcangel')
(94, 'Hamernik')
(95, 'Bennett')
(96, 'Williams')
(97, 'Okajima')
(98, 'Mcdonald')
(99, 'Dortch')
(100, 'Gillespie')
(101, 'Watson')
(102, 'Troyer')
(103, 'Robinson')
(104, 'Mcneal')
(105, 'Sanchez')
(106, 'Wells')
(107, 'Moreno')
(108, 'Sevillano')
(109, 'Rodriguez')
(110, 'Cooks')
(111, 'Weiland')
(112, 'Odom')
(113, 'Cruz')
(114, 'Stancil')
(115, 'Corriveau')
(116, 'Stillwell')
(117, 'Gonzales')
(118, 'Garrett')
(119, 'Earhart')
(120, 'Pidro')
(121, 'Patete')
(122, 'Gardner')
(123, 'Kay')
(124, 'Lang')
(125, 'Esposito')
(126, 'Nimmo')
(127, 'Emberton')
(128, 'Vasquez')
(129, 'Robinson')
(130, 'Schleck')
(131, 'Dandrea')
(132, 'Barth')
(133, 'Lobel')
(134, 'Hairston')
(135, 'Brown')
(136, 'Jones')
(137, 'Burris')
(138, 'Hale')
(139, 'Conn')
(140, 'Laitila')
(141, 'Houston')
(142, 'Walker')
(143, 'Manley')
(144, 'Delp')
(145, 'Yuengling')
(146, 'Elmer')
(147, 'Dunbar')
(148, 'Bailey')
(149, 'Thompson')
(150, 'Brown')
(151, 'Watkins')
(152, 'Richardson')
(153, 'Owczarzak')
(154, 'Brown')
(155, 'Phillips')
(156, 'Smith')
(157, 'Doherty')
(158, 'Blansett')
(159, 'Allard')
(160, 'Austin')
(161, 'Butler')
(162, 'Webster')
(163, 'Saenz')
(164, 'Wolfe')
(165, 'Gauthier')
(166, 'Williams')
(167, 'Sawyer')
(168, 'Mccane')
(169, 'Broyles')
(170, 'Haney')
(171, 'Coston')
(172, 'Brown')
(173, 'Giannini')
(174, 'Smith')
(175, 'Burton')
(176, 'Pritchard')
(177, 'Hinojosa')
(178, 'Williford')
(179, 'Thompson')
(180, 'Leech')
(181, 'Gomez')
(182, 'Blackman')
(183, 'Krebs')
(184, 'Music')
(185, 'Prince')
(186, 'Pickett')
(187, 'Villalobos')
(188, 'Spano')
(189, 'Marugg')
(190, 'Fenske')
(191, 'Rios')
(192, 'Driver')
(193, 'Gainey')
(194, 'Percy')
(195, 'Vessey')
(196, 'Warner')
(197, 'Salazar')
(198, 'Lint')
(199, 'Coleman')
(200, 'Morris')
(201, 'Evans')
(202, 'Krausmann')
(203, 'Pryor')
(204, 'Gossett')
(205, 'Hall')
(206, 'Tanner')
(207, 'Roberts')
(208, 'Johnson')
(209, 'Meyer')
(210, 'Nesbit')
(211, 'Taylor')
(212, 'Howard')
(213, 'Glover')
(214, 'Rivera')
(215, 'Allen')
(216, 'Parks')
(217, 'Ramirez')
(218, 'Hess')
(219, 'Allbritton')
(220, 'Lowrie')
(221, 'Johns')
(222, 'Kurtz')
(223, 'Adams')
(224, 'Flemings')
(225, 'Hogen')
(226, 'Bess')
(227, 'Cathey')
(228, 'Simons')
(229, 'Fillingham')
(230, 'Gath')
(231, 'Blodgett')
(232, 'Bryant')
(233, 'Shows')
(234, 'Stenger')
(235, 'Murray')
(236, 'Breland')
(237, 'Serrano')
(238, 'Henley')
(239, 'Davis')
(240, 'Winder')
(241, 'Lowe')
(242, 'Barbre')
(243, 'Robertson')
(244, 'Jebb')
(245, 'Parker')
(246, 'Conard')
(247, 'Juarez')
(248, 'Boyes')
(249, 'Craiger')
(250, 'Renyer')
(251, 'Zohn')
(252, 'Aivao')
(253, 'Rich')
(254, 'Glover')
(255, 'Simmons')
(256, 'King')
(257, 'Reed')
(258, 'Quick')
(259, 'Judd')
(260, 'Turner')
(261, 'Richardson')
(262, 'Paulino')
(263, 'Craft')
(264, 'Robinson')
(265, 'Paine')
(266, 'Willadsen')
(267, 'Billinger')
(268, 'Gunderson')
(269, 'Banda')
(270, 'Jones')
(271, 'Latch')
(272, 'Christie')
(273, 'Johnson')
(274, 'Burghard')
(275, 'Watkins')
(276, 'Thibodeau')
(277, 'Hernandez')
(278, 'Mcdaniel')
(279, 'Olberding')
(280, 'Meek')
(281, 'Ferguson')
(282, 'Clark')
(283, 'Lynch')
(284, 'Maccarone')
(285, 'Miller')
(286, 'Davis')
(287, 'Mcnay')
(288, 'Bachand')
(289, 'Macfarland')
(290, 'Manning')
(291, 'Floyd')
(292, 'Torres')
(293, 'Stavnes')
(294, 'Rice')
(295, 'Hunter')
(296, 'Welby')
(297, 'Franco')
(298, 'Story')
(299, 'Woodworth')
(300, 'Fender')
(301, 'Maines')
(302, 'Schaedler')
(303, 'Heath')
(304, 'Bender')
(305, 'Gabel')
(306, 'Ricardo')
(307, 'Banks')
(308, 'Mcconnell')
(309, 'Plagmann')
(310, 'Mathis')
(311, 'Gray')
(312, 'Justice')
(313, 'Joseph')
(314, 'Winkler')
(315, 'Robinson')
(316, 'Cleveland')
(317, 'Murray')
(318, 'Nakasone')
(319, 'Udo')
(320, 'Poteet')
(321, 'Prince')
(322, 'Emery')
(323, 'Hines')
(324, 'Gardiner')
(325, 'Taylor')
(326, 'Millen')
(327, 'Nolan')
(328, 'Wyman')
(329, 'Blackburn')
(330, 'Harper')
(331, 'Konty')
(332, 'Driggers')
(333, 'Woods')
(334, 'Burr')
(335, 'Elliott')
(336, 'Jean')
(337, 'Wages')
(338, 'Duvall')
(339, 'Gaskamp')
(340, 'Gordon')
(341, 'Orosco')
(342, 'Harmon')
(343, 'Mcdonald')
(344, 'Smith')
(345, 'Ecton')
(346, 'Fitzgerald')
(347, 'Davenport')
(348, 'Geib')
(349, 'Bryan')
(350, 'Smith')
(351, 'Campbell')
(352, 'Lindberg')
(353, 'Dostal')
(354, 'Johnson')
(355, 'Crawford')
(356, 'Cantrell')
(357, 'Perez')
(358, 'Castrey')
(359, 'Scott')
(360, 'Wells')
(361, 'Broussard')
(362, 'Nelson')
(363, 'Williams')
(364, 'Herrera')
(365, 'Talbott')
(366, 'Reed')
(367, 'Basso')
(368, 'Valdez')
(369, 'Williams')
(370, 'Raub')
(371, 'Rusin')
(372, 'Weitzman')
(373, 'Cannon')
(374, 'Hooper')
(375, 'Jolicoeur')
(376, 'Williams')
(377, 'Hernandez')
(378, 'Bridges')
(379, 'Tennison')
(380, 'Sanchez')
(381, 'Dibble')
(382, 'Shelley')
(383, 'Smith')
(384, 'Laflam')
(385, 'Roberts')
(386, 'Geary')
(387, 'Wood')
(388, 'Ruble')
(389, 'Enriquez')
(390, 'Bullock')
(391, 'Brown')
(392, 'Jeanlouis')
(393, 'Peters')
(394, 'Avalos')
(395, 'Nieves')
(396, 'Mcneill')
(397, 'Maestas')
(398, 'Palmer')
(399, 'Reilly')
(400, 'Pratt')
(401, 'Fish')
(402, 'Staples')
(403, 'Albert')
(404, 'Westervelt')
(405, 'Halstead')
(406, 'Archer')
(407, 'Lawrence')
(408, 'White')
(409, 'Smith')
(410, 'Fair')
(411, 'Allison')
(412, 'Bean')
(413, 'Vega')
(414, 'Watkins')
(415, 'Allen')
(416, 'Harty')
(417, 'Wallace')
(418, 'Gaines')
(419, 'Karathanasis')
(420, 'Rodgers')
(421, 'Contreras')
(422, 'Diaz')
(423, 'Vandermark')
(424, 'Williams')
(425, 'Moreno')
(426, 'Guthmiller')
(427, 'Clark')
(428, 'Blank')
(429, 'Smith')
(430, 'Bell')
(431, 'Stiles')
(432, 'Morales')
(433, 'Smith')
(434, 'Newkirk')
(435, 'Miller')
(436, 'Wright')
(437, 'Rochon')
(438, 'Christophe')
(439, 'Gerow')
(440, 'Garcia')
(441, 'Thomas')
(442, 'Rogers')
(443, 'Douglass')
(444, 'Testerman')
(445, 'Hill')
(446, 'Thompson')
(447, 'Mcclendon')
(448, 'Landry')
(449, 'Lee')
(450, 'Waterman')
(451, 'Winfield')
(452, 'Zuber')
(453, 'Obrien')
(454, 'Mcelroy')
(455, 'Chamberlain')
(456, 'Yates')
(457, 'Kramer')
(458, 'Carrol')
(459, 'Miller')
(460, 'Mckee')
(461, 'Galloway')
(462, 'Pesce')
(463, 'Marcotte')
(464, 'Griffith')
(465, 'Moyer')
(466, 'Thomas')
(467, 'Sanders')
(468, 'Craig')
(469, 'Murch')
(470, 'Sears')
(471, 'Snellgrove')
(472, 'Beckett')
(473, 'Hays')
(474, 'Wolfe')
(475, 'Young')
(476, 'Hicks')
(477, 'Lochrico')
(478, 'West')
(479, 'Hull')
(480, 'Mclain')
(481, 'Eagle')
(482, 'Jolly')
(483, 'Martin')
(484, 'Duenas')
(485, 'Hubbard')
(486, 'Warren')
(487, 'Fletcher')
(488, 'Berger')
(489, 'Gibson')
(490, 'Fuller')
(491, 'Rodgers')
(492, 'Lomeli')
(493, 'Morrison')
(494, 'Johnson')
(495, 'Mohamed')
(496, 'Mckibben')
(497, 'Barner')
(498, 'Ross')
(499, 'Hughes')
(500, 'Henkes')
(501, 'Mcintyre')
(502, 'Washington')
(503, 'Galarza')
(504, 'Sargeant')
(505, 'Murray')
(506, 'Duncan')
(507, 'Aldrich')
(508, 'Maenpaa')
(509, 'Hetz')
(510, 'Degroot')
(511, 'Troy')
(512, 'Bradley')
(513, 'Blanchard')
(514, 'Shelby')
(515, 'Moreno')
(516, 'Farrior')
(517, 'Brewer')
(518, 'Shackelford')
(519, 'Riggins')
(520, 'Fletcher')
(521, 'Kinnear')
(522, 'Ruckman')
(523, 'Eberhart')
(524, 'Pittman')
(525, 'Castleman')
(526, 'Ylonen')
(527, 'Taylor')
(528, 'Winters')
(529, 'Ortega')
(530, 'Turner')
(531, 'Buford')
(532, 'Murray')
(533, 'May')
(534, 'Tyler')
(535, 'Masters')
(536, 'Mcaninch')
(537, 'Spear')
(538, 'Gonzales')
(539, 'Seel')
(540, 'Mcguffey')
(541, 'Mora')
(542, 'Long')
(543, 'Goings')
(544, 'Vitt')
(545, 'Wyatt')
(546, 'Pereira')
(547, 'Polston')
(548, 'Mckenna')
(549, 'Scroggs')
(550, 'Evans')
(551, 'Brock')
(552, 'Thomson')
(553, 'Collura')
(554, 'Mendoza')
(555, 'Millick')
(556, 'Marriott')
(557, 'Brumleve')
(558, 'Caldwell')
(559, 'Salinas')
(560, 'Clemons')
(561, 'Perdue')
(562, 'Thurman')
(563, 'Rosel')
(564, 'Garvin')
(565, 'Ramsey')
(566, 'Boulware')
(567, 'Boren')
(568, 'Cunningham')
(569, 'Burdine')
(570, 'Bylsma')
(571, 'Hines')
(572, 'Hayes')
(573, 'Raygoza')
(574, 'Ramirez')
(575, 'Brown')
(576, 'Conover')
(577, 'Henderson')
(578, 'Miner')
(579, 'Walker')
(580, 'Castro')
(581, 'Bartlett')
(582, 'Williams')
(583, 'Ratcliff')
(584, 'Bryan')
(585, 'Maldomado')
(586, 'Morales')
(587, 'Posas')
(588, 'Holohan')
(589, 'Harrison')
(590, 'Barksdale')
(591, 'Daigle')
(592, 'Mayer')
(593, 'Hill')
(594, 'Pollard')
(595, 'Foster')
(596, 'Winnen')
(597, 'Hayes')
(598, 'Reed')
(599, 'Crain')
(600, 'Black')
(601, 'Seger')
(602, 'Bradley')
(603, 'Turner')
(604, 'Benson')
(605, 'Calder')
(606, 'Mccroy')
(607, 'Mitchell')
(608, 'Reed')
(609, 'Laughlin')
(610, 'Medford')
(611, 'Carroll')
(612, 'Culp')
(613, 'Tada')
(614, 'Bagdon')
(615, 'Nickerson')
(616, 'Ruble')
(617, 'Lescarbeau')
(618, 'Coleman')
(619, 'Berry')
(620, 'Janak')
(621, 'Leonard')
(622, 'Besse')
(623, 'Kisner')
(624, 'Smith')
(625, 'Fiedler')
(626, 'Brune')
(627, 'Marler')
(628, 'Oswald')
(629, 'Leray')
(630, 'Donati')
(631, 'Hairston')
(632, 'Dalton')
(633, 'Barbetta')
(634, 'Mclarney')
(635, 'Neal')
(636, 'Kirby')
(637, 'Webb')
(638, 'Mize')
(639, 'Rhodes')
(640, 'Roman')
(641, 'Steinke')
(642, 'Conaway')
(643, 'Johnson')
(644, 'Abbott')
(645, 'Hamilton')
(646, 'Lopez')
(647, 'Blanton')
(648, 'Harrell')
(649, 'Crespo')
(650, 'Phillips')
(651, 'Niemi')
(652, 'Sears')
(653, 'Young')
(654, 'Sanders')
(655, 'Kramp')
(656, 'Burditt')
(657, 'Young')
(658, 'Allen')
(659, 'Mcclallen')
(660, 'Hardie')
(661, 'Johnston')
(662, 'Davis')
(663, 'Love')
(664, 'Rivas')
(665, 'Mertens')
(666, 'Miller')
(667, 'Longley')
(668, 'Pitts')
(669, 'Roberson')
(670, 'Moise')
(671, 'Chambers')
(672, 'Diclaudio')
(673, 'Brunet')
(674, 'Lau')
(675, 'Muzii')
(676, 'Speer')
(677, 'Jones')
(678, 'Mullenax')
(679, 'Altman')
(680, 'Gorn')
(681, 'Smith')
(682, 'Cosgrove')
(683, 'Cook')
(684, 'Hoffman')
(685, 'Hardy')
(686, 'Wells')
(687, 'Hamby')
(688, 'Decook')
(689, 'Norwood')
(690, 'Stimpert')
(691, 'Spencer')
(692, 'Klein')
(693, 'Bradford')
(694, 'Hey')
(695, 'Colvin')
(696, 'Harrel')
(697, 'Defenbaugh')
(698, 'Gilfillan')
(699, 'Ochs')
(700, 'Broussard')
(701, 'Smith')
(702, 'Williams')
(703, 'Mckean')
(704, 'Oday')
(705, 'Paulino')
(706, 'Askew')
(707, 'Cobb')
(708, 'Hazelton')
(709, 'Burton')
(710, 'Briones')
(711, 'Williams')
(712, 'Jackson')
(713, 'Poplar')
(714, 'Washington')
(715, 'Sabo')
(716, 'Kearns')
(717, 'Raley')
(718, 'Akins')
(719, 'Dearman')
(720, 'Chambers')
(721, 'Portes')
(722, 'Nicole')
(723, 'Bowers')
(724, 'Simms')
(725, 'Aguilar')
(726, 'Covello')
(727, 'Dender')
(728, 'Deslauriers')
(729, 'Hiller')
(730, 'Street')
(731, 'Bartley')
(732, 'Mckillip')
(733, 'Todaro')
(734, 'Dixon')
(735, 'Gutierrez')
(736, 'Clawson')
(737, 'Ottesen')
(738, 'Sayle')
(739, 'Wilson')
(740, 'Robinson')
(741, 'Salcedo')
(742, 'Hyer')
(743, 'Paiz')
(744, 'Latham')
(745, 'Vereen')
(746, 'Bartkowski')
(747, 'Holcomb')
(748, 'Vinson')
(749, 'Jones')
(750, 'Bishop')
(751, 'Jackson')
(752, 'Breit')
(753, 'Jacobs')
(754, 'Kliebert')
(755, 'Mayo')
(756, 'Speck')
(757, 'Tracy')
(758, 'Allman')
(759, 'Barton')
(760, 'Facteau')
(761, 'Gustin')
(762, 'Morris')
(763, 'Lopez')
(764, 'Spears')
(765, 'Wells')
(766, 'Craft')
(767, 'Hopkins')
(768, 'Walters')
(769, 'Durfee')
(770, 'Roe')
(771, 'Hawks')
(772, 'Gordy')
(773, 'Robinson')
(774, 'Springer')
(775, 'Melendez')
(776, 'Schoemaker')
(777, 'Smith')
(778, 'Kearse')
(779, 'Macaraeg')
(780, 'Yengo')
(781, 'Drake')
(782, 'Joe')
(783, 'Pride')
(784, 'Herald')
(785, 'Harrington')
(786, 'Williams')
(787, 'Stancil')
(788, 'Eaton')
(789, 'Dorman')
(790, 'Moore')
(791, 'Lambert')
(792, 'Mccauley')
(793, 'Reed')
(794, 'Johnson')
(795, 'Jones')
(796, 'Kushner')
(797, 'Stagg')
(798, 'Perham')
(799, 'Trott')
(800, 'Hebel')
(801, 'Smith')
(802, 'Jones')
(803, 'Fisher')
(804, 'Ward')
(805, 'Myers')
(806, 'Flynn')
(807, 'Gullickson')
(808, 'Mueller')
(809, 'Rushton')
(810, 'Waters')
(811, 'Nemec')
(812, 'Pisano')
(813, 'Boyden')
(814, 'Hefley')
(815, 'Mcdowell')
(816, 'Murphy')
(817, 'Martin')
(818, 'Jochum')
(819, 'Hartl')
(820, 'Crain')
(821, 'Brushwood')
(822, 'Bennett')
(823, 'Neil')
(824, 'Faulk')
(825, 'Fleeman')
(826, 'King')
(827, 'Villeneuve')
(828, 'Lopez')
(829, 'Boyer')
(830, 'Perun')
(831, 'Burton')
(832, 'Dancy')
(833, 'Craig')
(834, 'Smith')
(835, 'Cotter')
(836, 'Stokes')
(837, 'Dyas')
(838, 'Snyder')
(839, 'Price')
(840, 'Carey')
(841, 'Moran')
(842, 'Buffin')
(843, 'Morales')
(844, 'Levine')
(845, 'Conyers')
(846, 'Kennedy')
(847, 'Fogle')
(848, 'Barbin')
(849, 'Johnson')
(850, 'Dedic')
(851, 'Campbell')
(852, 'Gresham')
(853, 'Blake')
(854, 'Mills')
(855, 'Greer')
(856, 'Frye')
(857, 'Sizemore')
(858, 'King')
(859, 'Ward')
(860, 'Perry')
(861, 'Fink')
(862, 'Mcnally')
(863, 'Burch')
(864, 'Guerette')
(865, 'Sabad')
(866, 'Whalen')
(867, 'Griggs')
(868, 'Avila')
(869, 'Cazier')
(870, 'Dalphonse')
(871, 'Gomez')
(872, 'Johnson')
(873, 'Mims')
(874, 'Ables')
(875, 'Miller')
(876, 'White')
(877, 'Westcott')
(878, 'Holt')
(879, 'Jackson')
(880, 'Davis')
(881, 'Montgomery')
(882, 'Garcia')
(883, 'Gleason')
(884, 'Harness')
(885, 'Howard')
(886, 'Nast')
(887, 'Welch')
(888, 'Diego')
(889, 'Morris')
(890, 'Capps')
(891, 'Gualtieri')
(892, 'Kindle')
(893, 'Castillo')
(894, 'Cox')
(895, 'Hitt')
(896, 'Dionne')
(897, 'Ramos')
(898, 'Valdez')
(899, 'Roark')
(900, 'Jones')
(901, 'Gauvin')
(902, 'Truman')
(903, 'Jensen')
(904, 'Klein')
(905, 'Pearsall')
(906, 'Davis')
(907, 'Mccammon')
(908, 'Collins')
(909, 'Gonzales')
(910, 'Mitchell')
(911, 'Cook')
(912, 'Barrientos')
(913, 'Cabello')
(914, 'Finley')
(915, 'Dupree')
(916, 'Feller')
(917, 'Longacre')
(918, 'Simms')
(919, 'Mason')
(920, 'Sneed')
(921, 'Evans')
(922, 'Nolie')
(923, 'Bogart')
(924, 'Johnson')
(925, 'Mcleod')
(926, 'Stone')
(927, 'Kingery')
(928, 'Smith')
(929, 'Bromley')
(930, 'Ng')
(931, 'Altman')
(932, 'Lopez')
(933, 'Knupp')
(934, 'Wageman')
(935, 'Brooks')
(936, 'Bridges')
(937, 'Castro')
(938, 'Soehl')
(939, 'Hegwood')
(940, 'Nelson')
(941, 'Jones')
(942, 'Moses')
(943, 'Wilson')
(944, 'Keith')
(945, 'Dragich')
(946, 'Kenney')
(947, 'Witherspoon')
(948, 'Blankenship')
(949, 'Layne')
(950, 'Johnson')
(951, 'Shorter')
(952, 'Rister')
(953, 'Boyd')
(954, 'Schon')
(955, 'Brown')
(956, 'Mosier')
(957, 'Chesnutt')
(958, 'Ramirez')
(959, 'Priem')
(960, 'Ledesma')
(961, 'Noyes')
(962, 'Gluck')
(963, 'Arceo')
(964, 'Finke')
(965, 'Metcalf')
(966, 'Guerrero')
(967, 'Piercy')
(968, 'Stratton')
(969, 'Corbett')
(970, 'Johnson')
(971, 'Perri')
(972, 'Early')
(973, 'Jackson')
(974, 'Pellowski')
(975, 'Anderson')
(976, 'Berg')
(977, 'Fisher')
(978, 'Newell')
(979, 'Zeigler')
(980, 'Lindauer')
(981, 'Morgon')
(982, 'Schulte')
(983, 'Long')
(984, 'Herman')
(985, 'Hadlock')
(986, 'Hickson')
(987, 'Adams')
(988, 'Lopez')
(989, 'Whitson')
(990, 'Porter')
(991, 'Works')
(992, 'Rich')
(993, 'Miller')
(994, 'Werner')
(995, 'Mitchell')
(996, 'Soto')
(997, 'Hull')
(998, 'White')
(999, 'Newby')
(1000, 'Cann')
(1001, 'Tomlin')
(1002, 'Bitting')
(1003, 'White')
(1004, 'Oliver')
(1005, 'Fudge')
(1006, 'Krell')
(1007, 'Mckinnon')
(1008, 'Waggoner')
(1009, 'Hall')
(1010, 'Harian')
(1011, 'Rogers')
(1012, 'Hubbard')
(1013, 'Standard')
(1014, 'Haney')
(1015, 'Hessler')
(1016, 'Cerda')
(1017, 'Finn')
(1018, 'Baldwin')
(1019, 'Custard')
(1020, 'Baker')
(1021, 'Brown')
(1022, 'Kempinski')
(1023, 'Caraballo')
(1024, 'Miller')
(1025, 'Nahass')
(1026, 'Bevington')
(1027, 'Ostermann')
(1028, 'Mitchell')
(1029, 'Hier')
(1030, 'Ussery')
(1031, 'Johnson')
(1032, 'Tom')
(1033, 'Burtch')
(1034, 'Lheureux')
(1035, 'Casey')
(1036, 'Elliott')
(1037, 'Greenstreet')
(1038, 'Tatom')
(1039, 'Cam')
(1040, 'Villalpando')
(1041, 'Tucker')
(1042, 'Rourke')
(1043, 'Labbe')
(1044, 'Carey')
(1045, 'Wellington')
(1046, 'Stclair')
(1047, 'Swanson')
(1048, 'Kapp')
(1049, 'Riley')
(1050, 'Jones')
(1051, 'Distaffen')
(1052, 'Fraser')
(1053, 'Gathers')
(1054, 'Gilmore')
(1055, 'Kaneta')
(1056, 'Holmes')
(1057, 'Edwards')
(1058, 'Gallo')
(1059, 'Nash')
(1060, 'Marino')
(1061, 'Diaz')
(1062, 'Gambrill')
(1063, 'Bowers')
(1064, 'Aubrey')
(1065, 'Garcia')
(1066, 'Perez')
(1067, 'Erickson')
(1068, 'Pickering')
(1069, 'Kohl')
(1070, 'Dennison')
(1071, 'Spease')
(1072, 'Bryan')
(1073, 'Testa')
(1074, 'Watkins')
(1075, 'Dutcher')
(1076, 'Flores')
(1077, 'King')
(1078, 'Williams')
(1079, 'Quarles')
(1080, 'Sanchez')
(1081, 'Brown')
(1082, 'Lyons')
(1083, 'Woolard')
(1084, 'Gray')
(1085, 'Mcculley')
(1086, 'Duarte')
(1087, 'Levine')
(1088, 'Stohr')
(1089, 'Cook')
(1090, 'Mitchell')
(1091, 'Wooten')
(1092, 'Oeltjen')
(1093, 'Dykes')
(1094, 'Powell')
(1095, 'Allard')
(1096, 'Callahan')
(1097, 'Hays')
(1098, 'Roberts')
(1099, 'Chappell')
(1100, 'Gray')
(1101, 'Garcia')
(1102, 'Miller')
(1103, 'Ford')
(1104, 'Couchman')
(1105, 'Gibson')
(1106, 'Greer')
(1107, 'Pecoraino')
(1108, 'Peterson')
(1109, 'Graham')
(1110, 'Hassell')
(1111, 'Davies')
(1112, 'Sanders')
(1113, 'Larrick')
(1114, 'Hoffman')
(1115, 'Smith')
(1116, 'Moreno')
(1117, 'Ratcliffe')
(1118, 'Pendergrass')
(1119, 'Little')
(1120, 'Rich')
(1121, 'Williams')
(1122, 'Dean')
(1123, 'Devera')
(1124, 'Roberts')
(1125, 'Smith')
(1126, 'Reynolds')
(1127, 'Golightly')
(1128, 'Puckett')
(1129, 'Bowman')
(1130, 'Garnes')
(1131, 'Smith')
(1132, 'Etheridge')
(1133, 'Mayo')
(1134, 'Flores')
(1135, 'Gregory')
(1136, 'Klein')
(1137, 'Hedges')
(1138, 'Terry')
(1139, 'Hayashi')
(1140, 'Webb')
(1141, 'Schwingenschloegl')

B) Erstelle einen Data Frame aus dem die Anzahl der Kunden je Kundenbetreuer ersichtlich ist. Die Anzahl soll bereits mittels 
SQL Statement berechnet werden. Die Sortierung (absteigend) soll im Data Frame erfolgen. 
Im Terminal sollen die "Top 5" Kundenbetreuer nach "Anzahl" ausgegeben werden.

In [15]:
my_df=pd.read_sql("SELECT m.ID, m.Vorname, m.Nachname, COUNT(k.ID) FROM C_Mitarbeiter m JOIN C_Kunden k ON k.[Kunden-Betreuer] = m.ID GROUP BY m.ID;", conn)
my_df_new=my_df.sort_values(by='COUNT(k.ID)', ascending=False)
my_df_new.head()

   ID   Vorname Nachname  COUNT(k.ID)
4   5     Fonda  Coleman          132
3   4    Minnie   Porter          125
2   3    Brandy    Nosek          122
5   6  Jonathan  Flowers          115
1   2      Joel   Jewett          114

In [16]:
my_df.sort_values(by='COUNT(k.ID)', ascending=False)
my_df.head()

   ID Vorname Nachname  COUNT(k.ID)
0   1  Norman    Brown          112
1   2    Joel   Jewett          114
2   3  Brandy    Nosek          122
3   4  Minnie   Porter          125
4   5   Fonda  Coleman          132

In [17]:
my_df_new.to_html('df_sorted.html')